title:       "Phase Shift"
description: "AI, Tech, Consciousness, Ethics. It may be a bit of each, maybe none."
url:         "https://cagriy.github.io"
baseurl:     ""

author:      "Cagri"

paginate:    5
permalink:   /:title

markdown:    kramdown
highlighter: rouge

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
