title:       "Phase Shift"
description: "AI, Tech, Consciousness, Ethics, etc."
url:         "https://cagriy.github.io"
baseurl:     ""

author:      "Cagri"

paginate:    5
permalink:   /:title

markdown:    kramdown
highlighter: rouge

google_site_verification: "BEZzAUZZvkXSKCrCb7XRcANxp0yjjWhxY0YGG_Z0ATw"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
